package com.lzf.bean;

// Generated 2016-1-21 13:46:58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Active generated by hbm2java
 */
@Entity
@Table(name="active")
public class Active implements java.io.Serializable {

	@Id
	private Integer activeId;
	private String activeName;
	private String ativeMessage;
	private Set<Club> clubs = new HashSet<Club>(0);

	public Active() {
	}

	public Active(String activeName, String ativeMessage) {
		this.activeName = activeName;
		this.ativeMessage = ativeMessage;
	}

	public Active(String activeName, String ativeMessage, Set<Club> clubs) {
		this.activeName = activeName;
		this.ativeMessage = ativeMessage;
		this.clubs = clubs;
	}

	public Integer getActiveId() {
		return this.activeId;
	}

	public void setActiveId(Integer activeId) {
		this.activeId = activeId;
	}

	public String getActiveName() {
		return this.activeName;
	}

	public void setActiveName(String activeName) {
		this.activeName = activeName;
	}

	public String getAtiveMessage() {
		return this.ativeMessage;
	}

	public void setAtiveMessage(String ativeMessage) {
		this.ativeMessage = ativeMessage;
	}

	public Set<Club> getClubs() {
		return this.clubs;
	}

	public void setClubs(Set<Club> clubs) {
		this.clubs = clubs;
	}

}
