package com.lzf.bean;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2016-1-21 13:46:58 by Hibernate Tools 3.4.0.CR1

/**
 * Apply generated by hbm2java
 */
@Entity
@Table(name="apply")
public class Apply implements java.io.Serializable {

	@Id
	private Integer applyId;
	private String applyName;
	private String applyMessage;

	public Apply() {
	}

	public Apply(String applyName, String applyMessage) {
		this.applyName = applyName;
		this.applyMessage = applyMessage;
	}

	public Integer getApplyId() {
		return this.applyId;
	}

	public void setApplyId(Integer applyId) {
		this.applyId = applyId;
	}

	public String getApplyName() {
		return this.applyName;
	}

	public void setApplyName(String applyName) {
		this.applyName = applyName;
	}

	public String getApplyMessage() {
		return this.applyMessage;
	}

	public void setApplyMessage(String applyMessage) {
		this.applyMessage = applyMessage;
	}

}
